name: "Create Golioth Artifact"
description: "Create an artifact in the Golioth Cloud."
branding:
  icon: "cpu"
  color: "green"

inputs:
  file:
    description: "File to use for artifact."
    required: true
  version:
    description: "Artifact semantic version."
    required: true

runs:
  using: "composite"
  steps:
    - run: goliothctl dfu artifact create provision ${{ inputs.file }} --version ${{ inputs.version }}
      shell: bash